version: '3'
services:
  sql-server:
    image: mcr.microsoft.com/mssql/server
    hostname: sql-server
    container_name: sql-server
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=superLongPassword2!
      - MSSQL_PID=Express